language: swift
osx_image: xcode11.5

jobs:
  include:
    - stage: "Analysis"
      name: "Analysis"
      script: fastlane analysis
    - stage: "Test"
      name: "Test"
      script: fastlane test
    - stage: "Build"
      name: "Build"
      script: fastlane build
