name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fastlane:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: install fastlane & plugins
      run: bundle install
    - name: Run fastlane analysis
      run: fastlane analysis
    - name: Run fastlane test
      run: fastlane test
    - name: Run fastlane build
      run: fastlane build
