name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@master
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
